export interface planAction {
    departement: "",
    zone: "",
    origine: "",
    prob: "",
    cause: "",
    support: "",
    date_debut: "",
    date_cloture: "",
    status: "",
    action: "",
    responsable: "",
    contol_effic: "",
    progress: "",
    annul: "",
    level: "",
    editeur: "",
    note: "",
    id_scrap: null,
    id_rapportnc: null,
    id_dmpp: null,
    id_supercontrole: null,
    id_suiviclient: null,
    id_suivifournisseur: null,
}